services:
  - type: web
    name: clinic-mobila-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: clinic-mobila-db
          property: connectionString
      - key: BACKEND_URL
        value: https://clinic-mobila-backend.onrender.com
      - key: FRONTEND_URL
        value: https://clinic-mobila.onrender.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ADMIN_EMAIL
        value: admin@clinicmobila.md

databases:
  - name: clinic-mobila-db
    databaseName: clinic_mobila
    user: clinic_user
    region: oregon
    ipAllowList: []
